name: flutter_template
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.2
  dio: 5.3.3
  get_it: 7.6.4
  flutter_dotenv: 5.1.0
  flutter_bloc: 8.1.3
  intl: 0.18.1
  mockito: 5.4.2
  bloc_test: 9.1.4

dev_dependencies:
  build_runner: 2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/i18n/
    - assets/images/